file_type: csv
dataset_name: testfile
file_name: Oct_2019
table_name: Oct_2019
inbound_delimiter: ","
outbound_delimiter: "|"
skip_leading_rows: 1
columns: 
    - event_time
    - event_type
    - product_id
    - category_id
    - category_code
    - brand
    - price
    - user_id
    - user_session
